import jsPDF from 'jspdf';

interface Receipt {
  id: string;
  invoice_id: string;
  amount: number;
  payment_method: 'credit_card' | 'bank_transfer' | 'credit_note' | 'cash';
  paid_at: string;
  receipt_url: string;
  status: 'completed' | 'processing' | 'failed';
  description: string;
  reference_number: string;
}

export const generateReceiptPDF = (receipt: Receipt, language: string = 'en') => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Colors
  const primaryColor = '#4F46E5'; // Indigo
  const textColor = '#1F2937'; // Gray-800
  const lightGray = '#F3F4F6'; // Gray-100

  // Header
  doc.setFillColor(primaryColor);
  doc.rect(0, 0, pageWidth, 40, 'F');

  // Title
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text("King's College", pageWidth / 2, 20, { align: 'center' });
  doc.setFontSize(14);
  doc.text(
    language === 'th' ? 'ใบเสร็จรับเงิน' : language === 'zh' ? '收据' : 'Payment Receipt',
    pageWidth / 2,
    32,
    { align: 'center' }
  );

  // Reset text color
  doc.setTextColor(textColor);

  // Receipt Info Box
  const startY = 55;
  doc.setFillColor(lightGray);
  doc.rect(15, startY, pageWidth - 30, 40, 'F');

  // Receipt details
  doc.setFontSize(10);
  doc.setFont(undefined, 'bold');
  doc.text('Receipt Number:', 20, startY + 10);
  doc.setFont(undefined, 'normal');
  doc.text(receipt.reference_number, 70, startY + 10);

  doc.setFont(undefined, 'bold');
  doc.text('Invoice ID:', 20, startY + 20);
  doc.setFont(undefined, 'normal');
  doc.text(receipt.invoice_id, 70, startY + 20);

  doc.setFont(undefined, 'bold');
  doc.text('Date:', 20, startY + 30);
  doc.setFont(undefined, 'normal');
  const formattedDate = new Date(receipt.paid_at).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
  doc.text(formattedDate, 70, startY + 30);

  // Description section
  const descY = startY + 50;
  doc.setFontSize(12);
  doc.setFont(undefined, 'bold');
  doc.text('Description:', 20, descY);
  doc.setFont(undefined, 'normal');
  doc.setFontSize(11);
  doc.text(receipt.description, 20, descY + 8);

  // Payment details
  const paymentY = descY + 25;
  doc.setFillColor(lightGray);
  doc.rect(15, paymentY, pageWidth - 30, 30, 'F');

  doc.setFontSize(10);
  doc.setFont(undefined, 'bold');
  doc.text('Payment Method:', 20, paymentY + 10);
  doc.setFont(undefined, 'normal');
  const paymentMethodLabels = {
    credit_card: 'Credit Card',
    bank_transfer: 'Bank Transfer',
    credit_note: 'Credit Note',
    cash: 'Cash'
  };
  doc.text(paymentMethodLabels[receipt.payment_method], 70, paymentY + 10);

  doc.setFont(undefined, 'bold');
  doc.text('Status:', 20, paymentY + 20);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(receipt.status === 'completed' ? '#10B981' : '#EF4444');
  doc.text(receipt.status.toUpperCase(), 70, paymentY + 20);
  doc.setTextColor(textColor);

  // Amount section
  const amountY = paymentY + 45;
  doc.setDrawColor(primaryColor);
  doc.setLineWidth(0.5);
  doc.line(15, amountY, pageWidth - 15, amountY);

  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.text('Total Amount:', 20, amountY + 15);
  doc.setTextColor(primaryColor);
  doc.setFontSize(18);
  const formattedAmount = new Intl.NumberFormat('th-TH', {
    style: 'currency',
    currency: 'THB'
  }).format(receipt.amount);
  doc.text(formattedAmount, pageWidth - 20, amountY + 15, { align: 'right' });

  doc.setTextColor(textColor);
  doc.line(15, amountY + 22, pageWidth - 15, amountY + 22);

  // Footer
  doc.setFontSize(9);
  doc.setFont(undefined, 'normal');
  doc.setTextColor(128, 128, 128);
  const footerY = doc.internal.pageSize.getHeight() - 30;
  doc.text(
    "King's College Parent Portal",
    pageWidth / 2,
    footerY,
    { align: 'center' }
  );
  doc.text(
    'This is an official receipt generated by the King\'s College payment system.',
    pageWidth / 2,
    footerY + 5,
    { align: 'center' }
  );
  doc.text(
    `Generated on: ${new Date().toLocaleString('en-US')}`,
    pageWidth / 2,
    footerY + 10,
    { align: 'center' }
  );

  // Download the PDF
  doc.save(`receipt-${receipt.reference_number}.pdf`);
};
